#!/bin/sh

. libtest.sh
. libgit.sh

export LINES=12

steps '
	<Enter>
	:maximize
	:view-close
	:save-display restored-split.screen
	:view-close
	:save-display closed.screen
'

tigrc <<EOF
set line-graphics = utf-8
set vertical-split = horizontal
EOF

in_work_dir create_repo_from_tgz "$base_dir/files/scala-js-benchmarks.tgz"

test_tig -n 3

assert_equals 'restored-split.screen' <<EOF
2014-03-01 17:26 -0500 Jonas Fonseca ∙ [master] WIP: Upgrade to 0.4-SNAPSHOT and
2014-03-01 15:59 -0500 Jonas Fonseca ∙ Add type parameter for js.Dynamic
2014-01-16 22:51 -0500 Jonas Fonseca ∙ Move classes under org.scalajs.benchmark
[main] ee912870202200a0b9cf4fd86ba57243212d341e - commit 1 of 3             100%
commit ee912870202200a0b9cf4fd86ba57243212d341e
Refs: [master]
Author:     Jonas Fonseca <jonas.fonseca@gmail.com>
AuthorDate: Sat Mar 1 17:26:01 2014 -0500
Commit:     Jonas Fonseca <jonas.fonseca@gmail.com>
CommitDate: Sat Mar 1 17:26:01 2014 -0500
[diff] ee912870202200a0b9cf4fd86ba57243212d341e - line 1 of 367               1%
EOF

assert_equals 'closed.screen' <<EOF
2014-03-01 17:26 -0500 Jonas Fonseca ∙ [master] WIP: Upgrade to 0.4-SNAPSHOT and
2014-03-01 15:59 -0500 Jonas Fonseca ∙ Add type parameter for js.Dynamic
2014-01-16 22:51 -0500 Jonas Fonseca ∙ Move classes under org.scalajs.benchmark







[main] ee912870202200a0b9cf4fd86ba57243212d341e - commit 1 of 3             100%
EOF
