#!/bin/sh
#
# The pager view shares the internal diff-highlight buffering: a +/- run
# ending the piped-in diff must survive the end-of-stream flush.

. libtest.sh
. libgit.sh

tigrc <<EOF
set diff-highlight = internal
EOF

steps '
	:save-display pager.screen
'

git_init

test_tig <<EOF
diff --git a/file.txt b/file.txt
index a92d664..834e8b4 100644
--- a/file.txt
+++ b/file.txt
@@ -1,3 +1,4 @@
 line 1
 line 2
 line 3
+line 4 added at eof
EOF

assert_equals 'pager.screen' <<EOF
diff --git a/file.txt b/file.txt
index a92d664..834e8b4 100644
--- a/file.txt
+++ b/file.txt
@@ -1,3 +1,4 @@
 line 1
 line 2
 line 3
+line 4 added at eof



















[pager] - line 1 of 9                                                       100%
EOF
