#!/bin/sh
#
# With "diff-highlight = internal", +/- lines are buffered so word refinement
# can pair them, and a run at the very end of the diff is only emitted by the
# end-of-stream flush.  The stage and log views used to skip that flush and
# silently dropped a change touching the end of a file.

. libtest.sh
. libgit.sh

export TEST_TIME_NOW=1401046937

export LINES=24

tigrc <<EOF
set vertical-split = no
set diff-highlight = internal
EOF

steps '
	:enter
	:save-display stage.screen
'

add_eof_change()
{
	git init -q .
	git_config
	printf 'line 1\nline 2\nline 3\n' > file.txt
	git add file.txt
	git_commit --author="$IDENT_A" --message="Initial commit"
	printf 'line 4 added at eof\n' >> file.txt
}

in_work_dir add_eof_change

test_tig

assert_equals 'stage.screen' <<EOF
2014-05-25 19:42 +0000 Not Committed Yet o Unstaged changes
2009-02-13 23:31 +0000 A. U. Thor        I [master] Initial commit





[main] Unstaged changes                                                     100%
 file.txt | 1 +
 1 file changed, 1 insertion(+)

diff --git a/file.txt b/file.txt
index a92d664..834e8b4 100644
--- a/file.txt
+++ b/file.txt
@@ -1,3 +1,4 @@
 line 1
 line 2
 line 3
+line 4 added at eof


[stage] Press '<Enter>' to jump to file diff - line 1 of 12                 100%
EOF
